In [1]:
from sklearn.datasets import make_classification
X,y = make_classification(n_classes= 2,n_samples=400,n_redundant=0,random_state=1)

import warnings
warnings.simplefilter("ignore")

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold,cross_val_score

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# GridSearchCV

In [5]:
from sklearn.model_selection import GridSearchCV

In [6]:
 # Exploring the GridSearchCV Class
# GridSearchCV(
#     estimator=,     # A sklearn model
#     param_grid=,    # A dictionary of parameter names and values
#     cv=,            # An integer that represents the number of k-folds
#     scoring=,       # The performance measure (such as r2, precision)
#     n_http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python3#jobs=,        # The number of jobs to run in parallel
#     verbose=        # Verbosity (0-3, with higher being more)
# )

In [7]:
model_dt = DecisionTreeClassifier()

In [8]:
import numpy as np
# 'entropy', 

In [9]:
import numpy as np
hyper = {
    "max_depth":np.arange(1,1000,10),
    "criterion":['gini', 'log_loss','entropy',],
    "random_state":np.arange(1,50,5),

}

In [10]:
grid_model=GridSearchCV(
    estimator=model_dt,   
    param_grid=hyper,   
    cv=5,            
    scoring='accuracy',   
    n_jobs=5,    
    verbose=1
)

# grid_model=GridSearchCV(model_dt,hyper,cv=5,scoring='accuracy',n_jobs=5,verbose=1)

In [11]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 3000 candidates, totalling 15000 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=5,
             param_grid={'criterion': ['gini', 'log_loss', 'entropy'],
                         'max_depth': array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991]),
                         'random_state': array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])},
             scoring='accuracy', verbose=1)

In [12]:
print(grid_model.best_params_)

{'criterion': 'log_loss', 'max_depth': 1, 'random_state': 1}


In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,classification_report

In [14]:
y_preds=grid_model.predict(X_test)
y_preds

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1])

In [15]:
accuracy_score(y_preds,y_test)

0.9416666666666667

In [16]:
confusion_matrix(y_preds,y_test)

array([[51,  1],
       [ 6, 62]], dtype=int64)

In [17]:
f1_score(y_preds,y_test)

0.9465648854961831

In [18]:
print(classification_report(y_preds,y_test))

              precision    recall  f1-score   support

           0       0.89      0.98      0.94        52
           1       0.98      0.91      0.95        68

    accuracy                           0.94       120
   macro avg       0.94      0.95      0.94       120
weighted avg       0.95      0.94      0.94       120



In [19]:
import pandas as pd
spprt=pd.DataFrame(y_preds).value_counts(normalize=False)
spprt

1    68
0    52
Name: count, dtype: int64

# RandomizedSearchCV

In [20]:
from sklearn.model_selection import RandomizedSearchCV

In [21]:
class sklearn.grid_search.RandomizedSearchCV(estimator, 
                                             param_distributions=random_search, 
                                             n_iter=10, scoring=None, # Number of parameter combinations to try
                                             fit_params=None,
                                             n_jobs=1,Use all processors to compute in parallel 
                                             iid=True, 
                                             refit=True,
                                              cv=None, Number of folds for k-fold validation 
                                             verbose=0, 
                                             pre_dispatch='2*n_jobs', 
                                             random_state=None, 
                                             error_score='raise'
)

In [22]:
randomsearch= random_model=RandomizedSearchCV(
                               estimator=model_dt,  
                               param_distributions=hyper,
                               cv=5,
                               verbose=1,
                               n_jobs=1)

In [23]:
randomsearch.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=1,
                   param_distributions={'criterion': ['gini', 'log_loss',
                                                      'entropy'],
                                        'max_depth': array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991]),
                                        'random_state': array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])},
                   verbose=1)

In [24]:
randomsearch.best_params_

{'random_state': 31, 'max_depth': 471, 'criterion': 'log_loss'}

In [25]:
y2_preds=randomsearch.predict(X_test)
y2_preds

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1])

In [26]:
accuracy_score(y2_preds,y_test)

0.9083333333333333

In [27]:
confusion_matrix(y2_preds,y_test)

array([[52,  6],
       [ 5, 57]], dtype=int64)

In [28]:
f1_score(y2_preds,y_test)

0.912

In [29]:
print(classification_report(y2_preds,y_test))

              precision    recall  f1-score   support

           0       0.91      0.90      0.90        58
           1       0.90      0.92      0.91        62

    accuracy                           0.91       120
   macro avg       0.91      0.91      0.91       120
weighted avg       0.91      0.91      0.91       120



# BayesianRandomhSearchCV

In [30]:
# !pip install scikit-optimize
# !pip install git+https://github.com/scikit-optimize/scikit-optimize.git
# import skops

from skopt import BayesSearchCV
from scipy.stats import loguniform, randint

In [31]:
from skopt.space import Real, Categorical, Integer
classifier= DecisionTreeClassifier()

In [32]:


# param_grid = {
#     "classifier__learning_rate": loguniform(1e-4, 0.1),
#     "classifier__n_estimators": randint(100,1000),
#     "classifier__max_depth": randint(4, 400) 
# }

# Random
reg_rand = RandomizedSearchCV(
                         classifier,
                         param_distributions=hyper,
#                          n_iter=n_iter,
                         cv=5,
                         n_jobs=1,
                         scoring='accuracy',
                         verbose=1
                              )

model_rand = reg_rand.fit(X, y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [33]:
model_rand.best_params_

{'random_state': 1, 'max_depth': 551, 'criterion': 'entropy'}

In [34]:
y3_preds=model_rand.predict(X_test)
y3_preds

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1])

In [35]:
accuracy_score(y3_preds,y_test)

1.0

In [36]:
confusion_matrix(y3_preds,y_test)

array([[57,  0],
       [ 0, 63]], dtype=int64)

In [37]:
f1_score(y3_preds,y_test)

1.0

In [38]:
print(classification_report(y3_preds,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        57
           1       1.00      1.00      1.00        63

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [39]:
# _= opt.fit(X_train, y_train)

In [40]:
# from skopt import BayesSearchCV
# # parameter ranges are specified by one of below
# from skopt.space import Real, Categorical, Integer

# from sklearn.datasets import load_iris
# from sklearn.svm import SVC
# from sklearn.model_selection import train_test_split

# # X, y = load_iris(True)
# X_train, X_test, y_train, y_test = train_test_split(X, y,
#                                                    train_size=0.75,
#                                                     random_state=0)

#  # log-uniform: understand as search over p = exp(x) by varying x
# opt = BayesSearchCV(
#    SVC(),
#     {
#         'C': Real(1e-6, 1e+6, prior='log-uniform'),
#        'gamma': Real(1e-6, 1e+1, prior='log-uniform'),
#         'degree': Integer(1,8),
#         'kernel': Categorical(['linear', 'poly', 'rbf']),
#      },
#    n_iter=32,
#      random_state=0
# )

# # executes bayesian optimization
# _ = opt.fit(X_train, y_train)

#  # model can be saved, used for predictions or scoring
# print(opt.score(X_test, y_test))

In [41]:
from skopt import BayesSearchCV
# parameter ranges are specified by one of below
from skopt.space import Real, Categorical, Integer

In [42]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   train_size=0.75,
                                                    random_state=0)

In [44]:
opt = BayesSearchCV(
   SVC(),
    {
        'C': Real(1e-6, 1e+6, prior='log-uniform'),
       'gamma': Real(1e-6, 1e+1, prior='log-uniform'),
        'degree': Integer(1,8),
        'kernel': Categorical(['linear', 'poly', 'rbf']),
     },
   n_iter=32,
     random_state=0
)

In [45]:
# # executes bayesian optimization
# _ = opt.fit(X_train, y_train)

In [46]:
#  # model can be saved, used for predictions or scoring
# print(opt.score(X_test, y_test))

In [47]:
v=pd.DataFrame(y_preds)
j=pd.DataFrame(y2_preds)
l=pd.DataFrame(y3_preds)

In [48]:
vji=pd.concat(([v,j]),axis=1)
vji.columns=["Prediction1","Prediction2"]
vji=pd.concat([vji,l],axis=1)
vji.columns=["Prediction1","Prediction2","Prediction3"]

In [55]:
print(vji[(vji['Prediction1']-vji['Prediction2']==1) | (vji['Prediction1']-vji['Prediction2']==-1)].iloc[:,[0,1]])

     Prediction1  Prediction2
19             1            0
24             1            0
75             1            0
87             1            0
93             1            0
118            1            0


In [56]:
print(vji[(vji['Prediction1']-vji['Prediction3']==1) | (vji['Prediction1']-vji['Prediction3']==-1)].iloc[:,[0,2]])

    Prediction1  Prediction3
27            1            0
32            1            0
45            0            1
65            1            0
68            1            0
74            1            0
87            1            0


In [57]:
print(vji[(vji['Prediction2']-vji['Prediction3']==1) | (vji['Prediction2']-vji['Prediction3']==-1)].iloc[:,[0,2]])

     Prediction1  Prediction3
19             1            1
24             1            1
27             1            0
32             1            0
45             0            1
65             1            0
68             1            0
74             1            0
75             1            1
93             1            1
118            1            1


In [52]:
xx=pd.DataFrame(X_test)
xx


0         1         2         3         4         5         6    
0  -1.996746 -2.484895 -0.575952  2.384293  0.341389  0.324869 -0.475650  \
1  -0.404769 -0.767909 -1.330030  0.243175  0.406133  0.187248  1.263359   
2  -1.957391 -1.040540  1.412296 -1.193967 -0.129926 -2.285775 -0.157830   
3  -0.949440 -0.819411  1.156107 -0.547322 -0.019117 -0.203386  1.424146   
4   1.271048  0.193059 -2.571591  0.239677 -1.256026 -0.110646  0.278080   
..       ...       ...       ...       ...       ...       ...       ...   
95 -1.641585  0.221543 -1.161871  1.655217  0.406610  0.233406  1.653776   
96  0.173680 -0.732032  0.380743 -0.697716  0.138595  2.084123 -2.003942   
97 -1.261575 -0.881258  1.160621  0.797587 -0.939589 -2.089441 -0.086479   
98  1.640057 -0.633792 -0.921659 -0.745680  0.188583  0.560918 -0.430770   
99  0.723692 -1.141416  0.245179 -0.939431  1.124703 -1.639476  2.095819   

          7         8         9         10        11        12        13   
0  -2.148997 -0.359021  0.436182 -1.214373  0.246853 -0.874541 -0.343500  \
1  -1.758870  0.564172 -0.518453 -0.635143  2.787361  0.006784 -0.139311   
2  -0.015923  1.448543 -0.679315  0.400154 -1.102078  0.226002  2.717386   
3  -1.189724  1.285717  0.166552  0.163424 -0.623277 -0.844528 -0.460537   
4  -4.542827  0.334034 -0.426308 -1.716695 -0.663857  0.994198 -0.657083   
..       ...       ...       ...       ...       ...       ...       ...   
95  2.020592 -1.246745  0.365872  0.611944  0.217673  0.391605 -0.202189   
96 -0.856643  0.892588 -0.877247 -1.540079  1.303575 -0.080607  0.420593   
97  0.476819 -0.568480  0.461626 -1.025365 -1.280209 -0.912972  0.648588   
98 -1.054214 -1.258350 -0.417871 -1.070288 -0.447473 -1.407064 -0.113782   
99  0.631497  2.338143  0.927357 -0.072090 -1.445851  1.424365  0.257968   

          14        15        16        17        18        19  
0  -0.081702 -1.393557  1.208443 -0.569165 -0.824905  0.145388  
1   0.464322  1.580018  1.053783  0.258468  0.260543 -1.385539  
2  -1.121314  0.732108  0.477698  1.438281  0.698800  0.629873  
3   0.947821 -0.605011 -0.454874 -2.108903 -0.387564 -0.342545  
4  -0.840332 -0.626635  1.513822 -0.032491  0.830995  0.491127  
..       ...       ...       ...       ...       ...       ...  
95 -0.592053 -0.045796 -0.469671 -1.294483  0.710068  0.047745  
96  0.317427 -0.198500 -0.044161 -0.129782 -1.087234  1.133613  
97 -1.434808  1.396319 -1.836104 -0.323274 -0.471558  0.660448  
98  1.177070 -0.472876 -0.896880  0.944285  0.647375  1.386826  
99 -0.697385 -0.816293 -1.130405  0.823185  1.058974 -1.144458  

[100 rows x 20 columns]

In [53]:
xx.iloc[[27,32,65,68,74,87],:]

0         1         2         3         4         5         6    
27  2.382766 -0.401759  1.222996 -1.163063 -0.457645  1.031118  0.363118  \
32 -0.148937  0.058098 -0.008131  1.049827 -0.293695  1.336392 -1.353253   
65 -1.288487 -0.373687  0.841409  0.450585  0.661060  0.989528 -1.068135   
68 -0.551323 -0.512483 -0.258695  0.548488  0.088120 -0.628069  0.242411   
74 -0.550871 -0.486735  0.617037 -1.200913 -0.539159 -1.461658 -1.220669   
87  0.327751 -0.899702 -0.782005  0.405069 -0.665696  0.903518 -0.590562   

          7         8         9         10        11        12        13   
27  1.364129 -0.614908 -1.077009  0.419161  0.088642  0.080526  0.805295  \
32  0.563943 -1.172663 -0.581251  3.118480  0.351517  0.623651 -0.435145   
65  0.328059  1.300321 -0.416476  0.364444 -0.022161 -0.007400 -0.534328   
68 -2.410303 -0.732807 -0.768158  0.260688 -0.233441  2.301635  0.500320   
74 -0.299420  0.837728 -1.300110  0.278067  0.417224 -0.644936  0.046424   
87  0.222473  0.163965 -0.081397  1.738585 -1.395863 -0.360068  0.304355   

          14        15        16        17        18        19  
27  0.462314 -1.379569  1.946349  0.031152 -0.814204 -0.301463  
32 -0.617073 -0.214191  0.983467 -1.372419 -0.443988  0.305031  
65 -0.331306  0.645128 -0.111816  1.548697 -2.925305  0.585105  
68 -1.215225 -1.111373 -1.060274  0.313962 -0.904289  1.628239  
74 -0.275215  0.064998 -1.077913  0.318884 -1.220435  0.452660  
87  1.295183  1.598200  0.134388 -1.196205 -0.287442  0.293720

In [54]:
len(X_test)

100