In [1]:
import pandas as pd
import numpy as np

In [2]:
#importin the data
data =pd.read_csv("Advertising.csv")
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
#Independent varaible and dependent variable
xx = data.TV.values
y = data.sales.values

In [4]:
#Inverse of (X'x)
xmut= np.vstack((np.ones(len(xx)),xx)).T
xmut[:5]

array([[  1. , 230.1],
       [  1. ,  44.5],
       [  1. ,  17.2],
       [  1. , 151.5],
       [  1. , 180.8]])

In [5]:
#Coefficientts of the Model
beta_hat = np.linalg.inv(xmut.T.dot(xmut)).dot(xmut.T).dot(y)
beta_hat

array([7.03259355, 0.04753664])

In [6]:
#Predictions
yhat = xmut.dot(beta_hat)
yhat[:5]

array([17.97077451,  9.14797405,  7.85022376, 14.23439457, 15.62721814])