In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
iris = pd.read_csv(r"C:\Users\user\Desktop\irisec.csv")
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
irisd = iris.drop(["Species"],axis = "columns")
irisd.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [26]:
iris.Species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [28]:
iris["Species"] = le.fit_transform(iris["Species"])
target= iris["Species"]

In [29]:
target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [30]:
X = irisd
y = target

In [31]:
from sklearn.svm import SVC

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20)

In [39]:
SVC_Classification = SVC(kernel = "poly",degree = 8)
SVC_Classification.fit(X_train,y_train)

SVC(degree=8, kernel='poly')

In [41]:
y_pred = SVC_Classification.predict(X_test)

In [42]:
from sklearn.metrics import classification_report,confusion_matrix

In [44]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]


In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.82      0.90      0.86        10
           2       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

